name: Audit

on:
  push:
    branches: [master, develop]
    tags:
      - v*
  pull_request:
    branches: [master, develop]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - name: Tidy
        run: go mod tidy

      - name: Verify dependency
        run: go mod verify

      - name: Install golangci-linter
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: golangci-lint run --enable-all --disable lll --disable goerr113 ./...

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Run test
        run: 
          go test -race -v -coverprofile coverage.out ./...

      - name: Go Coverage Badge
        uses: tj-actions/coverage-badge-go@v1
        with:
          filename: coverage.out
